### ISSUE TITLE
Front-end crashing when CRM configured

### ISSUE THREAD

**Issue by Codewow** [twilio/flex-plugin-library-callback-and-voicemail#51]
Trying to implement this plugin, but it looks like the .replace is failing when a CRM embed is configured. I am guessing the Flex UI elements load a bit differently when a CRM is configured versus when it is not.

twilio-flex.unbundled-react.min.js:683 TypeError: Cannot read properties of undefined (reading 'replace')
    at _regeneratorRuntime.mark._regeneratorRuntime.wrap.e.CRMContainer.defaultProps.uriCallback (bundle.js?releaseSid=FK8b8bb876c959da9c6eea333623c13554:2:18325)
    at n.render (twilio-flex.unbundled-react.min.js:1285:62853)
    at Te (react-dom.min.js:119:308)
    at Ch (react-dom.min.js:119:105)
    at Pj (react-dom.min.js:233:139)
    at di (react-dom.min.js:168:305)
    at Nj (react-dom.min.js:168:236)
    at sc (react-dom.min.js:168:96)
    at gf (react-dom.min.js:162:109)
    at react-dom.min.js:73:230
    
    
[DynamicComponent: An error has been detected inside the AgentDesktopView.Panel2 DynamicComponent

[Original error:
"Cannot read properties of undefined (reading 'replace')"](twilio-flex.unbundled-react.min.js:683 1/8/2024, 2:40:59 PM - DynamicComponent: An error has been detected inside the AgentDesktopView.Panel2 DynamicComponent)](https://assets.flex.twilio.com/releases/flex-ui/2.5.0/twilio-flex.unbundled-react.min.js)

**Comment by brprigge** [comment]
Seeing the same issue.
